version: '2'
volumes:
  mysql_data: {}
services:
  rancher:            
    image: rancher/server:v1.6.7
    scale: 3
    command:
      - --advertise-address eth0
  rancher-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
      - ${PUBLIC_PORT}:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - protocol: http
        service: rancher
        source_port: 80
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  mysql:
    image: mysql:5.7.19
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: cattle
      MYSQL_PASSWORD: cattle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cattle

